DEFAULT_APP_NAME = "EnergyScope"
DEFAULT_APP_VERSION = "0.1.0"
DEFAULT_ENVIRONMENT = "development"
DEFAULT_DEBUG = False
DEFAULT_API_PREFIX = "/api/v1"
DEFAULT_CORS_ORIGINS = ["http://localhost:3000"]
DEFAULT_LOG_LEVEL = "INFO"
